In [1]:
import pandas as pd  #importing pandas

# Data-mining or Data-engg
  # -Imputer  -LabelEncoding  -OneHotEncoder
    

In [2]:
df=pd.read_csv('info.csv')

In [3]:
df.info
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
# for supply compatible(2-D)data   as here we removing headers simply
x=df.iloc[:,0:].values
x

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [5]:
#removing misssing values or replacing misssing value with some relevent data
#df.describe
from sklearn.preprocessing import Imputer

In [6]:
imp=Imputer(missing_values='NaN',axis=0,strategy='mean') #here axis=0 means coulmn-side whereas strategy='mean' is replacing 'NaN' values with total means values of coulmn-side

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [7]:
impute=imp.fit(x[:,1:3])  #this is only fitting of columns that we want to process  i.e. age & salary for replacing 'NaN' values with mean-value of coulmn-side(respective)

In [8]:
#time for transforming the fitted columns:-
x[:,1:3]=impute.transform(x[:,1:3])

In [9]:
#lets checkout for transformation
print(x)
print(x.shape)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 63777.77777777778 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' 38.77777777777778 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]
(10, 4)


In [10]:
# sring label   int/float
from sklearn.preprocessing import LabelEncoder


In [11]:
cont=LabelEncoder()#this is for country labelling

In [12]:
#now applying coulmn first in this Labelling
x[:,0]=cont.fit_transform(x[:,0])

In [13]:
x

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [14]:
p=LabelEncoder()#this is for purchase labelling

In [15]:
#now applying coulmn last in this labelling
x[:,3]=cont.fit_transform(x[:,3])

In [16]:
x

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [17]:
# now encoding first colmn----------making subcoulmn of first coulumns-- depending upon the factors(catagory)in coulmns
#           f|G|S     whereas f-france  ,G-germany ,S-spain
# france:   1|0|0
#spain:     0|0|1
#germany:   0|1|0
#for this we use dummy-variable concept:--------
from sklearn.preprocessing import OneHotEncoder

In [18]:
OneHotEncoder()  #acknowledge Encoder

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [19]:
first_col=OneHotEncoder(categorical_features=[0])   #defining exact column-number where we want to make catagory

In [20]:
x=first_col.fit_transform(x).toarray()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [22]:
x
x.astype(int)  #for print as integers
    #here you can see that first coulmn is subgrouped as three coulmns

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])