In [1]:
import numpy as np

#creating 1D array

a=np.array([2,3,5,6])
b=np.array([12,13,14,14])

#add same D array
c=a+b
print(c)

#multi
m=a*b
print(m)

#add particular value in each element of array
a5=a+5
print(a5)

[14 16 19 20]
[24 39 70 84]
[ 7  8 10 11]
