In [2]:
import numpy as np #importing numpy library


In [37]:
#here np is the object(instance) of imported library

In [19]:
#for 1-D array
x=np.array([1,2,3,4,5])
y=np.array([5,4,3,2,1])
x
y

array([5, 4, 3, 2, 1])

In [28]:
#for multidimentional arrays:-----
np.array([[x],[y]])

array([[[1, 2, 3, 4, 5]],

       [[5, 4, 3, 2, 1]]])

In [29]:
#or best method for M-d arrays
np.array([x,y])

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [31]:
#another method:-
np.array([[1,34,45,67],[66,44,33,22]])

array([[ 1, 34, 45, 67],
       [66, 44, 33, 22]])

In [35]:
#multidimentiona character array or matrix:-
char_array=np.array([['v','d','a','n'],['b','h','a','t']])
char_array

array([['v', 'd', 'a', 'n'],
       ['b', 'h', 'a', 't']], dtype='<U1')

In [36]:
type(char_array)  #for checking 

numpy.ndarray