In [1]:
import numpy as np


In [15]:
#now creating arrays
from numpy import array

l=[1.0,33.87,48.44,55,48]  #list of float numbers
farray=array(l)   #creating array
print(farray)   #displaying
print(farray.dtype)  #for displaying datatype
print(type(farray)) #for displying  type

[ 1.   33.87 48.44 55.   48.  ]
float64
<class 'numpy.ndarray'>


In [32]:
#now creating empty array
from numpy import empty
E=empty([6,3])  #here we the arguments to the function is an array or tuple that specifies length as here its 6x3
print(E)# displaying random numbers of matrix

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23058707e-307 8.45593934e-307 7.56593017e-307]
 [1.11261027e-306 1.11261502e-306 1.42410839e-306]
 [7.56597770e-307 6.23059726e-307 1.42419530e-306]
 [1.37961302e-306 1.78019082e-306 1.33511562e-306]
 [8.45596650e-307 2.22522596e-306 2.22522596e-306]]


In [34]:
#now creating  zeros 
Z=np.zeros([3,5])
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
#noe creating ones
O=np.ones([5,3])
print(O)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#combining arrays :--------

#by using vertical-stack:-----
a1=np.array([1,2,3,4,5])
a2=np.array([5,4,3,2,1])
print(a1,a2)
a3=np.vstack((a1,a2))  #combining a1 & a2 vertically as matrix
print(a3)    
print(a3.shape)     #for displaying shape(i.e order of matrix here..)

[1 2 3 4 5] [5 4 3 2 1]
[[1 2 3 4 5]
 [5 4 3 2 1]]
(2, 5)


In [46]:
#by using horizontal-stack:-----
a4=np.hstack((a1,a2)) #here its combining a1 & a2 horizontally... as merging two arrays
print(a4) 
print(a4.shape)   #for displaying shape (i.e numbers of coulmns)

[1 2 3 4 5 5 4 3 2 1]
(10,)


# concept of  subsetting of matrix:-------


In [49]:
#first of all creating matrix
M=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(M)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [55]:
#exploration of matrix
print(M.shape)
print(M.dtype)
print(type(M))

(4, 5)
int32
<class 'numpy.ndarray'>


In [61]:
#now practising subsetting  using squre-bracket'[]'  :-----
# to see coulmns:-
print(M[0:,0])  #here '0:' means all raws from zeroth raw & ',0' means zeroth coulms
print(M[0:,1])  #for 1st coulmn
print(M[1:3,0:])  #all coulmns from 1st to 2nd rows
print(M[1:3,1:4])  #similary we can try thoe

[ 1  6 11 16]
[ 2  7 12 17]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  8  9]
 [12 13 14]]


In [64]:
# to see rows:-----
print(M[2,0:]) #whole second row
print(M[3,1:3])  #3rd row from 1st to 3rd coulmn

[11 12 13 14 15]
[17 18]


In [102]:
#susetting discreately:--
print(M[[0,3],0:])  #displaying zeroth & 3rd row
print(M)
print(M[[0,3],[0,4]]) #fail to subset corner elements of matrix its assume combination of 0*0 &3*4
   #but it can subset elements irrelevent to correspondents
print(M[[0,3,0,3],[0,0,4,4]])   #this one can subsets the corner elements of matrix
print(M[[1,3],[0,3]])  #for subset 6 & 19 irrelevent to correspondents



[[ 1  2  3  4  5]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1 20]
[ 1 16  5 20]
[ 6 19]


In [98]:
#method 2 to subsets corners of matrix
c=M[0:,[0,4]]
print(c)
print(c[[0,3],0:])


[[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]]
[[ 1  5]
 [16 20]]
