In [1]:
import numpy as np

low=int(input("Enter the First element (100-124):"))
arr=np.arange(low,low+80,5).reshape(8,2)
print(arr)

Enter the First element (100-124):102
[[102 107]
 [112 117]
 [122 127]
 [132 137]
 [142 147]
 [152 157]
 [162 167]
 [172 177]]


In [8]:
f=open("file.txt","w")
a=np.random.random((3,2))
b=np.random.random((5,2))

f.write("matrix a:\n")
f.write(str(a))
f.write("\n")
f.write("matrix b:\n")
f.write(str(b))

print(a)
print(b)

[[0.96801869 0.52649688]
 [0.6220483  0.14648747]
 [0.36088558 0.26311726]]
[[0.85109176 0.74611236]
 [0.56789674 0.61700695]
 [0.88554146 0.94805891]
 [0.33227218 0.36035275]
 [0.17145406 0.88197562]]
